_security_logout:
    resource: security.route_loader.logout
    type: service
# Ce bloc de configuration déclare automatiquement la route de déconnexion "/logout".
# Je n’ai pas besoin de l’écrire moi-même dans mes fichiers de routing, Symfony la génère grâce à ce loader.
# Cette route est activée dès que j’utilise le système de sécurité avec authentification, notamment quand je mets en place le LoginFormAuthenticator.
# Elle permet à l’utilisateur connecté de se déconnecter simplement en accédant à /logout.
